In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.sample(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
445,9110720,B,11.990,24.89,77.61,441.3,0.10300,0.09218,0.05441,0.04274,...,30.36,84.48,513.9,0.1311,0.18220,0.16090,0.12020,0.2599,0.08251,NaN
269,8910720,B,10.710,20.39,69.50,344.9,0.10820,0.12890,0.08448,0.02867,...,25.21,76.51,410.4,0.1335,0.25500,0.25340,0.08600,0.2605,0.08701,NaN
349,899147,B,11.950,14.96,77.23,426.7,0.11580,0.12060,0.01171,0.01787,...,17.72,83.09,496.2,0.1293,0.18850,0.03122,0.04766,0.3124,0.07590,NaN
241,883539,B,12.420,15.04,78.61,476.5,0.07926,0.03393,0.01053,0.01108,...,20.37,83.85,543.4,0.1037,0.07776,0.06243,0.04052,0.2901,0.06783,NaN
103,862980,B,9.876,19.40,63.95,298.3,0.10050,0.09697,0.06154,0.03029,...,26.83,72.22,361.2,0.1559,0.23020,0.26440,0.09749,0.2622,0.08490,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [ ]:
df.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
97,B,9.787,19.94,62.11,294.5,0.10240,0.05301,0.006829,0.007937,0.1350,...,10.92,26.29,68.81,366.1,0.1316,0.09473,0.02049,0.02381,0.1934,0.08988
419,B,11.160,21.41,70.95,380.3,0.10180,0.05978,0.008955,0.010760,0.1615,...,12.36,28.92,79.26,458.0,0.1282,0.11080,0.03582,0.04306,0.2976,0.07123
486,B,14.640,16.85,94.21,666.0,0.08641,0.06698,0.051920,0.027910,0.1409,...,16.46,25.44,106.00,831.0,0.1142,0.20700,0.24370,0.07828,0.2455,0.06596
49,B,13.490,22.30,86.91,561.0,0.08752,0.07698,0.047510,0.033840,0.1809,...,15.15,31.82,99.00,698.8,0.1162,0.17110,0.22820,0.12820,0.2871,0.06917
188,B,11.810,17.39,75.27,428.9,0.10070,0.05562,0.023530,0.015530,0.1718,...,12.57,26.48,79.57,489.5,0.1356,0.10000,0.08803,0.04306,0.3200,0.06576

#### Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

#### Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.89756805, -0.39520651, -0.86977836, ..., -0.2471099 ,
        -1.02045852, -0.04551085],
       [ 1.91412127,  0.88231187,  1.78694355, ...,  1.31542065,
        -0.11501584, -0.46361831],
       [-1.09328368, -0.73462099, -1.04059905, ..., -0.26498223,
        -0.47855193,  0.74622454],
       ...,
       [-0.33798675, -1.19424476, -0.33811394, ..., -0.85981007,
        -0.77753487,  0.9619502 ],
       [-1.23634905, -0.93261277, -1.15021233, ...,  0.6463539 ,
         0.37083145,  2.35193509],
       [-0.373822  , -0.3056388 , -0.37371825, ..., -0.54269076,
        -0.18806281, -0.24566868]])

In [10]:
y_train

534    B
23     M
320    B
37     B
470    B
      ..
87     M
416    B
336    B
152    B
79     B
Name: diagnosis, Length: 455, dtype: object

#### Label Encoding

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0])

#### Numpy Arrays to PyTorch Tensor

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
print(X_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([455, 30])
torch.Size([455])

### Defining the model

In [36]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

##### Important Parameters

In [37]:
learning_rate = 0.1
epochs = 25

#### Training Pipeline

In [45]:
# Create Model
model = MySimpleNN(X_train_tensor)

# Define Loop

for epoch in range(epochs):
  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Loss Calculation
  loss = model.loss_function(y_pred, y_train_tensor)




  # Backward Pass
  loss.backward()

  # Parameter Update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print loss in each epochs
  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.66834686879486
Epoch: 2, Loss: 3.5453243192494854
Epoch: 3, Loss: 3.4159649337333464
Epoch: 4, Loss: 3.281543773349499
Epoch: 5, Loss: 3.1436785723903715
Epoch: 6, Loss: 3.0057291524138985
Epoch: 7, Loss: 2.8598302544648138
Epoch: 8, Loss: 2.707362939820004
Epoch: 9, Loss: 2.5481255571980803
Epoch: 10, Loss: 2.3888241800889025
Epoch: 11, Loss: 2.2299119961909577
Epoch: 12, Loss: 2.074518936655835
Epoch: 13, Loss: 1.9245620633712615
Epoch: 14, Loss: 1.7758062592798736
Epoch: 15, Loss: 1.6333317550371944
Epoch: 16, Loss: 1.4995388337544022
Epoch: 17, Loss: 1.3737670500342445
Epoch: 18, Loss: 1.2587802596690105
Epoch: 19, Loss: 1.1589110423632727
Epoch: 20, Loss: 1.0748294250637729
Epoch: 21, Loss: 1.006451188509626
Epoch: 22, Loss: 0.9526904871875098
Epoch: 23, Loss: 0.9114787405890937
Epoch: 24, Loss: 0.8801809109907248
Epoch: 25, Loss: 0.856191391182302

In [31]:
print(model.weights)
print(model.bias)

tensor([[-0.2725],
        [-0.1281],
        [-0.0471],
        [-0.0157],
        [-0.4031],
        [ 0.2682],
        [-0.2010],
        [ 0.3793],
        [ 0.4446],
        [ 0.2824],
        [-0.0839],
        [ 0.2630],
        [-0.1268],
        [ 0.4362],
        [ 0.5097],
        [-0.2146],
        [-0.3752],
        [-0.0898],
        [ 0.3493],
        [ 0.1358],
        [ 0.1255],
        [ 0.4818],
        [-0.1007],
        [ 0.0162],
        [-0.2103],
        [ 0.0141],
        [-0.5164],
        [ 0.3119],
        [ 0.4058],
        [ 0.3188]], dtype=torch.float64, requires_grad=True)
tensor([-0.1369], dtype=torch.float64, requires_grad=True)

### Evaluation

In [46]:
# Model Evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.6184980273246765