In [34]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim

In [35]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.sample(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
248,88466802,B,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.016150,...,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147,NaN
92,861853,B,13.270,14.76,84.74,551.7,0.07355,0.05055,0.03261,0.026480,...,22.35,104.50,830.6,0.10060,0.12380,0.13500,0.10010,0.2027,0.06206,NaN
364,9010877,B,13.400,16.95,85.48,552.4,0.07937,0.05696,0.02181,0.014730,...,21.70,93.76,663.5,0.12130,0.16760,0.13640,0.06987,0.2741,0.07582,NaN
467,9113514,B,9.668,18.10,61.06,286.3,0.08311,0.05428,0.01479,0.005769,...,24.62,71.11,380.2,0.13880,0.12550,0.06409,0.02500,0.3057,0.07875,NaN
270,8910721,B,14.290,16.82,90.30,632.6,0.06429,0.02675,0.00725,0.006250,...,20.65,94.44,684.6,0.08567,0.05036,0.03866,0.03333,0.2458,0.06120,NaN

In [36]:
df.shape

(569, 33)

In [37]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [38]:
df.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
451,M,19.59,25.00,127.70,1191.0,0.10320,0.09871,0.165500,0.090630,0.1663,...,21.44,30.96,139.80,1421.0,0.15280,0.18450,0.39770,0.1466,0.2293,0.06091
308,B,13.50,12.71,85.69,566.2,0.07376,0.03614,0.002758,0.004419,0.1365,...,14.97,16.94,95.48,698.7,0.09023,0.05836,0.01379,0.0221,0.2267,0.06192
336,B,12.99,14.23,84.08,514.3,0.09462,0.09965,0.037380,0.020980,0.1652,...,13.72,16.91,87.38,576.0,0.11420,0.19750,0.14500,0.0585,0.2432,0.10090
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.243900,0.138900,0.1726,...,25.45,26.40,166.10,2027.0,0.14100,0.21130,0.41070,0.2216,0.2060,0.07115
19,B,13.54,14.36,87.46,566.3,0.09779,0.08129,0.066640,0.047810,0.1885,...,15.11,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.1288,0.2977,0.07259

#### Train Test Split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

#### Scaling

In [40]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [41]:
X_train

array([[-0.39512502, -0.12270295, -0.42387222, ..., -0.50503998,
        -0.2615663 , -0.66639493],
       [-0.19359777, -0.14324037, -0.19183628, ...,  0.4193102 ,
         1.01062843,  0.1269504 ],
       [-0.95364339,  1.1026966 , -0.96459512, ..., -1.28820878,
         0.25618737, -0.45068506],
       ...,
       [ 2.63066268,  0.60751652,  2.50178026, ...,  1.84508699,
         1.12732846,  0.41715802],
       [-1.0630439 , -0.89399727, -1.05915914, ..., -1.10203553,
        -0.47359875, -0.0932071 ],
       [-0.45846215, -0.29841201, -0.52593471, ..., -1.54093896,
        -1.1014778 , -1.62096671]])

In [42]:
y_train

362    B
526    B
549    B
386    B
18     M
      ..
562    M
566    M
164    M
226    B
360    B
Name: diagnosis, Length: 455, dtype: object

#### Label Encoding

In [43]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [44]:
y_train

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0])

#### Numpy Arrays to PyTorch Tensor

In [45]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [46]:
print(X_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([455, 30])
torch.Size([455])

### Defining the model

In [47]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [48]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)
train_dataset[9]

(tensor([ 1.5539, -0.1090,  1.5603,  1.6322,  1.3596,  1.1018,  1.6148,  1.4677,
         -0.0839,  0.3721,  2.6406, -0.0734,  2.2487,  2.1686, -0.3281,  0.3641,
          0.7595,  0.8956, -0.1790,  0.3749,  2.0049,  0.0769,  1.8940,  2.0528,
          0.7367,  0.9858,  1.6110,  1.2773,  0.1066,  0.8297]),
 tensor(1.))

In [49]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [50]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

##### Important Parameters

In [51]:
learning_rate = 0.1
epochs = 25

In [55]:
# Create Model
model = MySimpleNN(X_train_tensor.shape[1])

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define Loss Function
loss_function = nn.BCELoss()

#### Training Pipeline

In [58]:
# Define Loop

for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:

    # Forward Pass
    y_pred = model(batch_features)

    # Loss Calculation
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # Clear Gradients
    optimizer.zero_grad()

    # Backward Pass
    loss.backward()

    # Parameter Update
    optimizer.step()

  # Print loss in each epochs
  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.07334893196821213
Epoch: 2, Loss: 0.0643625482916832
Epoch: 3, Loss: 0.10984279960393906
Epoch: 4, Loss: 0.04048902913928032
Epoch: 5, Loss: 0.01143342349678278
Epoch: 6, Loss: 0.05302124843001366
Epoch: 7, Loss: 0.02063250169157982
Epoch: 8, Loss: 0.10696426779031754
Epoch: 9, Loss: 0.011610597372055054
Epoch: 10, Loss: 0.3195059895515442
Epoch: 11, Loss: 0.036319535225629807
Epoch: 12, Loss: 0.22832301259040833
Epoch: 13, Loss: 0.017121054232120514
Epoch: 14, Loss: 0.09262901544570923
Epoch: 15, Loss: 0.06383385509252548
Epoch: 16, Loss: 0.05501696094870567
Epoch: 17, Loss: 0.003790173912420869
Epoch: 18, Loss: 0.025915736332535744
Epoch: 19, Loss: 0.17377257347106934
Epoch: 20, Loss: 0.01764567568898201
Epoch: 21, Loss: 0.01066172681748867
Epoch: 22, Loss: 0.001710730604827404
Epoch: 23, Loss: 0.00768593605607748
Epoch: 24, Loss: 0.10915422439575195
Epoch: 25, Loss: 0.11615004390478134

### Evaluation

In [60]:
# Model Evaluation using test_loader
model.eval() # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    # Forwars Pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float() # Convert probabilities to binary predictions

    # Calculate the batch accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    print(batch_accuracy)
    accuracy_list.append(batch_accuracy)


# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy:.4f}")

0.96875
1.0
0.96875
1.0
Accuracy: 0.9844